# Generated by Django 2.0.6 on 2018-06-03 12:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stringFormatter', '0002_auto_20180522_1117'),
    ]

    operations = [
        migrations.CreateModel(
            name='RandomList',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
    ]
